/**
 * Pass 6b — the emitter.
 *
 * Pure function: (tree) → TypeScript source. No model involved, so output is
 * syntactically valid by construction and identical for identical input.
 *
 * The generated file has no imports and no dependency on SKITE — it is a plain
 * React component using Tailwind classes. Exported projects must stand alone;
 * a tool whose output requires the tool is a trap.
 */

import type { DesignTokens } from "../design/tokens.ts";
import type { ComponentNode, ComponentTree } from "../ir/schema.ts";
import { emit, IMAGE_DECORATION_CLASSES, IMAGE_DECORATION_STYLE } from "./classes.ts";

const INDENT = "  ";

function escapeText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * A JS identifier that needs no quoting as an object key.
 *
 * CSS custom properties do not qualify — `--sk-bg: "#fff"` is a syntax error,
 * not a style — and the first version of token emission produced exactly that.
 * The code validator caught it, which is the argument for having one.
 */
const BARE_KEY = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function styleEntries(style: Record<string, string | number>): string {
  return Object.entries(style)
    .map(([k, v]) => {
      const key = BARE_KEY.test(k) ? k : JSON.stringify(k);
      return `${key}: ${typeof v === "number" ? v : JSON.stringify(v)}`;
    })
    .join(", ");
}

function styleToJsx(style: Record<string, string | number>): string {
  return `{{ ${styleEntries(style)} }}`;
}

function renderNode(
  node: ComponentNode,
  totalColumns: number,
  depth: number,
  tokens?: DesignTokens,
): string {
  const pad = INDENT.repeat(depth);
  const e = emit(node, totalColumns, tokens);

  // The root carries every design token. Inlining ~50 custom properties into
  // the JSX would bury the markup, so they are hoisted to a named constant and
  // spread here — the emitted page then reads as "these are the tokens, this is
  // the structure", which is also how it is meant to be edited.
  if (node.component === "Page" && tokens && e.style) {
    const vars = Object.fromEntries(
      Object.entries(e.style).filter(([k]) => k.startsWith("--")),
    ) as Record<string, string | number>;
    const rest = Object.fromEntries(
      Object.entries(e.style).filter(([k]) => !k.startsWith("--")),
    ) as Record<string, string | number>;
    if (Object.keys(vars).length > 0) {
      e.style = { __HOISTED__: 1, ...rest };
      hoisted = vars;
    }
  }

  const attrs = [`className="${e.className.replace(/\s+/g, " ").trim()}"`];
  if (e.style) {
    const { __HOISTED__: isRoot, ...rest } = e.style;
    attrs.push(
      isRoot
        ? `style={{ ...designTokens, ${styleEntries(rest as Record<string, string | number>)} }}`
        : `style=${styleToJsx(e.style)}`,
    );
  }
  // The back-reference that makes fidelity measurable after rendering.
  if (node.irNode) attrs.push(`data-ir-node="${node.irNode}"`);

  const open = `${pad}<${e.tag} ${attrs.join(" ")}>`;
  const close = `${pad}</${e.tag}>`;

  const inner: string[] = [];

  if (e.decoration === "image") {
    inner.push(`${pad}${INDENT}<div className="${IMAGE_DECORATION_CLASSES.wrap}">`);
    inner.push(
      `${pad}${INDENT}${INDENT}<span className="${IMAGE_DECORATION_CLASSES.label}" style=${styleToJsx(IMAGE_DECORATION_STYLE)}>Image</span>`,
    );
    inner.push(`${pad}${INDENT}</div>`);
  }

  if (e.text) {
    inner.push(`${pad}${INDENT}${escapeText(e.text)}`);
  }

  for (const child of node.children) {
    inner.push(renderNode(child, totalColumns, depth + 1, tokens));
  }

  if (inner.length === 0) {
    return `${pad}<${e.tag} ${attrs.join(" ")} />`;
  }

  return [open, ...inner, close].join("\n");
}

/** Filled by `renderNode` when it reaches the Page root. */
let hoisted: Record<string, string | number> | null = null;

export function emitTsx(
  tree: ComponentTree,
  totalColumns: number,
  tokens?: DesignTokens,
): string {
  hoisted = null;
  const body = renderNode(tree.root, totalColumns, 2, tokens);
  const tokenBlock = hoisted
    ? `/** Design tokens, derived from the sketch. Override these to retheme. */\n` +
      `const designTokens = {\n` +
      Object.entries(hoisted)
        .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
        .join("\n") +
      `\n} as React.CSSProperties;\n\n`
    : "";

  return `// Generated by SKITE from a sketch.
// Layout (order, proportions, spans, spacing) is derived from the drawing.
// Appearance (colour, type, radius, shadow) is added by the generator.
//
// No SKITE runtime, no imports, no lock-in — this is a plain React component.

${tokenBlock}export default function GeneratedPage() {
  return (
${body}
  );
}
`;
}

/** Flat list of the components used, for the run report. */
export function usedComponents(tree: ComponentTree): Record<string, number> {
  const counts: Record<string, number> = {};
  const walk = (n: ComponentNode) => {
    counts[n.component] = (counts[n.component] ?? 0) + 1;
    n.children.forEach(walk);
  };
  walk(tree.root);
  return counts;
}
