/**
 * Pass 6b — the emitter.
 *
 * Pure function: (tree) → TypeScript source. No model involved, so output is
 * syntactically valid by construction and identical for identical input.
 *
 * The generated file has no imports and no dependency on SKITE — it is a plain
 * React component using Tailwind classes. Exported projects must stand alone;
 * a tool whose output requires the tool is a trap.
 */

import type { ComponentNode, ComponentTree } from "../ir/schema.ts";
import { emit, IMAGE_DECORATION_CLASSES } from "./classes.ts";

const INDENT = "  ";

function escapeText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function styleToJsx(style: Record<string, string | number>): string {
  const entries = Object.entries(style)
    .map(([k, v]) => `${k}: ${typeof v === "number" ? v : JSON.stringify(v)}`)
    .join(", ");
  return `{{ ${entries} }}`;
}

function renderNode(node: ComponentNode, totalColumns: number, depth: number): string {
  const pad = INDENT.repeat(depth);
  const e = emit(node, totalColumns);

  const attrs = [`className="${e.className.replace(/\s+/g, " ").trim()}"`];
  if (e.style) attrs.push(`style=${styleToJsx(e.style)}`);
  // The back-reference that makes fidelity measurable after rendering.
  if (node.irNode) attrs.push(`data-ir-node="${node.irNode}"`);

  const open = `${pad}<${e.tag} ${attrs.join(" ")}>`;
  const close = `${pad}</${e.tag}>`;

  const inner: string[] = [];

  if (e.decoration === "image") {
    inner.push(`${pad}${INDENT}<div className="${IMAGE_DECORATION_CLASSES.wrap}">`);
    inner.push(`${pad}${INDENT}${INDENT}<span className="${IMAGE_DECORATION_CLASSES.label}">Image</span>`);
    inner.push(`${pad}${INDENT}</div>`);
  }

  if (e.text) {
    inner.push(`${pad}${INDENT}${escapeText(e.text)}`);
  }

  for (const child of node.children) {
    inner.push(renderNode(child, totalColumns, depth + 1));
  }

  if (inner.length === 0) {
    return `${pad}<${e.tag} ${attrs.join(" ")} />`;
  }

  return [open, ...inner, close].join("\n");
}

export function emitTsx(tree: ComponentTree, totalColumns: number): string {
  const body = renderNode(tree.root, totalColumns, 2);

  return `// Generated by SKITE from a sketch.
// Layout (order, proportions, spans, spacing) is derived from the drawing.
// Appearance (colour, type, radius, shadow) is added by the generator.
//
// No SKITE runtime, no imports, no lock-in — this is a plain React component.

export default function GeneratedPage() {
  return (
${body}
  );
}
`;
}

/** Flat list of the components used, for the run report. */
export function usedComponents(tree: ComponentTree): Record<string, number> {
  const counts: Record<string, number> = {};
  const walk = (n: ComponentNode) => {
    counts[n.component] = (counts[n.component] ?? 0) + 1;
    n.children.forEach(walk);
  };
  walk(tree.root);
  return counts;
}
